ALTER TABLE "categories" ALTER COLUMN "parent_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "featured_banner" ALTER COLUMN "category_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "featured_banner" ALTER COLUMN "product_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "order_item" ALTER COLUMN "quantity" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "order_item" ALTER COLUMN "product_image" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "order_item" ALTER COLUMN "product_sku" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_status" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_method" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_amount" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_currency" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_description" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_metadata" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "payment" ALTER COLUMN "payment_gateway_order_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "coupon" ALTER COLUMN "description" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "coupon" ALTER COLUMN "discount_percentage" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "coupon" ALTER COLUMN "discount_fixed_amount" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "coupon_transaction" ALTER COLUMN "discount_percentage" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "coupon_transaction" ALTER COLUMN "discount_fixed_amount" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "coupon" ADD CONSTRAINT "coupon_code_unique" UNIQUE("code");